name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.0-noble
    
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: 
          node-version: '24'
      - name: Install dependencies
        run: npm ci
      - name: Check style
        run: npm run eslint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: Trigger deployment on render
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true
  
  success_notification:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ needs.simple_deployment_pipeline.result == 'success' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v6
      - uses: sarisia/actions-status-discord@v1.16.0
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ needs.simple_deployment_pipeline.result }}
          content: ":white_check_mark: **Deployment Successful!** A new version deployed to production"
          title: "Deployment Details"
          nodetail: true
          nodate: true
          description: |
            **Commit:** ${{ github.event.head_commit.id }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}

  failure_notification:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ needs.simple_deployment_pipeline.result == 'failure' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v6
      - uses: sarisia/actions-status-discord@v1.16.0
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEB_HOOK }}
          status: ${{ needs.simple_deployment_pipeline.result }}
          content: ":x: **Build Failed!** The pipeline encountered an error"
          title: "Failure Details"
          nodetail: true
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.repository.Branch }}
            **Commit:** ${{ github.event.head_commit.id }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **Workflow:** ${{ github.workflow }}
            **Job:** simple_deployment_pipeline